apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: deployment-unidad3
    aplicacion: reserva-hotel
  name: deployment-unidad3
  namespace: unidad04
spec:
  replicas: 4
  selector:
    matchLabels:
      app: deployment-unidad3
  strategy:
    type: RollingUpdate
    rollingUpdate:
        maxUnavailable:25½
        maxSurge: 1
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: deployment-unidad3
    spec:
      containers:
      - image: ghcr.io/go-elevate/k8s4arch-hotels:monolith-v2
        name: k8s4arch-hotels
        resources: {}
        ports:
          -contarinerPort: 80
           protocol. TCP
status: {}
