apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob-unidad04
spec:
  template:
    spec:
     schedule: "0 2 * * *"
     jobTemplate:
       spec:
	restartPolicy: Never
         containers:
           -name: daily-report
             image: ghcr.io/go-elevate/k8s4arch-hotels-backend:slim
	     imagePullPolicy: Always
	     command: ["python"]
	     args: ["report.py"]

