apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: deployment-unidad4-01
    aplicacion: reserva-hotel
  name: deployment-unidad4-01
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployment-unidad4-01
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: deployment-unidad4-01
    spec:
      containers:
      - image: ghcr.io/go-elevate/k8s4arch-hotels:monolith-v2
        name: deployment-unidad4-01
        resources: {}
status: {}
