apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: deployment-unidad7-Frontend
    aplicacion: reserva-hotel-frontend
  name: deployment-unidad7-Frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployment-unidad7-Frontend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 1
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: deployment-unidad7-Frontend
    spec:
      containers:
       - name: frontend
         image: ghcr.io/go-elevate/k8s4arch-hotels-frontend:stable
         ports:
           - containerPort: 80
         envFrom:
          - configMapRef:
             name:
               name: configMapFrontend


         livenessProbe:
           tcpSocket:
            port: 80
           initialDelaySeconds: 60
           periodSeconds: 20
         readinessProbe:
           httpGet:
             path: /status
             port: 80
           initialDelaySeconds: 60
           periodSeconds: 20
         envFrom:
           - configMapRef:
              name: unidad05-1
         resources:
           requests:
             memory: "500m"
             cpu: "1"
           limits:
             memory: "1G"
             cpu: "2"
