apiVersion: networking.k8s.io/v1
kind: NetworkingPolicy
metadata:
  name: conexionFrontendBackend
spec:
  podSelector:
   matchLabels:
    app: deployment-unidad7-Backend
  policyTypes:
   - Ingress:
   ingress:
    - from:
      -podSelector:
        matchLabels:
          app: deployment-unidad7-Frontend
        ports:
         - protocol: TCP
           port: 5000   
