##BACKEND##
apiVersion: v1
kind: Service
metadata:
  name: Service-Backend
spec:
 type: ClusterIP
 selectir:
  app: deployment-unidad7-Backend
  tier: backend
 ports:
  -protocol: TCP
   name: http
   port: 80
   targetPort: 5000

##FRONTED##
apiVersion: v1
kind: Service
metadata:
  name: Service-Frontend
spec:
 type: ClusterIP
 selectir:
  app: deployment-unidad7-Frontend
  tier: frontend
 ports:
  -protocol: TCP
   name: http
   port: 80
   targetPort: 80
