apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: deployment-unidad6-01
    aplicacion: reserva-hotel-backend
  name: deployment-unidad6-01
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployment-unidad6-01
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 1
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: deployment-unidad6-01
    spec:
      containers:
       - name: frontend
         image: ghcr.io/go-elevate/k8s4arch-hotels-frontend:slim
         ports:
           - containerPort: 5000
         livenessProbe:
           tcpSocket:
            port: 5000
           initialDelaySeconds: 60
           periodSeconds: 20
         readinessProbe:
           httpGet:
             path: /status
             port: 5000
           initialDelaySeconds: 60
           periodSeconds: 20
         envFrom:
           - configMapRef:
              name: unidad05-1
         resources:
           requests:
             memory: "500m"
             cpu: "1"
           limits:
             memory: "1G"
             cpu: "2"
       - name: backend
         image: ghcr.io/go-elevate/k8s4arch-hotels:monolith-v2
         ports:
           - containerPort: 80
         livenessProbe:
           tcpSocket:
            port: 80
           initialDelaySeconds: 60
           periodSeconds: 20
         readinessProbe:
           httpGet:
             path: /
             port: 80
           initialDelaySeconds: 60
           periodSeconds: 20
         command: ["docker run --entrypoint python ghcr.io/go-elevate/k8s4arch-hotels-backend:slim"]
         args: ["migrations.py"]

